# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66cf31c32bfe1f095cdfe5a2c9a462b0e61f4568d3d96f54d9a2796d3574423c42ae422929c1871f57dd07022b9562ee36d9039dc9986095786531c3bc83b84a

test:
  secret_key_base: 6fc79f1722736b60c5ffb637b17467a904863cb7505947d11eb4833ac92dabc6ce3668184fbc7627de7a0d5c08638f272486e41c7d9aca314189e3ba6f8dbee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
